# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: kricsleo
subtitle: kricsleo's blog
description: It's my personal blog.
keywords:
  - blog
  - kricsleo
  - IT
  - Web Front End
author: kricsleo
motto: Developers' lives matter.
avatar: /images/avatar_blog.png
favicon: /images/favicon.ico
language: zh-CN
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://kricsleo.github.io
root: /
# permalink: :year/:month/:day/:title/
permalink: :title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: code
i18n_dir: :lang
skip_render:
  - '*.html'
  - code/**

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace: true

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# disable disqus for now
# disqus_shortname: kricsleo

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: materialCard

autoprefixer:
  exclude:
    - '*.min.css'
  # remove: false # prevent autoprefixer remove page-break-inside
  # browsers:
  #   - 'last 2 versions'
  #   - '> 5%'

all_minifier: true

image_minifier:
  enable: false # 图片不压缩
  interlaced: false
  multipass: false
  optimizationLevel: 2
  pngquant: false
  progressive: false

# synchronize articles to elasticsearch
elasticsearch:
  host: http://59.110.169.144
  port: 9200
  index: blog
  type: article

# Generator json content
jsonContent:
  meta: false
  keywords: false
  dateFormat: YYYY-MM-DD
  pages: false
  # pages:
  #   title: true
  #   slug: false
  #   date: false
  #   updated: false
  #   comments: false
  #   path: false
  #   link: false
  #   permalink: true
  #   excerpt: false
  #   keywords: false
  #   text: true
  #   raw: false
  #   content: false
  posts:
    title: true
    slug: false
    subtitle: true
    date: true
    updated: true
    comments: false
    path: true
    link: true
    permalink: false
    excerpt: false
    keywords: false
    text: true
    raw: false
    content: false
    categories: false
    tags: false

feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
- type: git
  repo: git@github.com:kricsleo/kricsleo.github.io.git
  branch: master
- type: git
  repo: root@aliyun.com:/workspace/kricsleo.github.io/kricsleo.github.io.git
  branch: master
